module.exports = {
    ...require('./uploadJob'),
    ...require('./uploadMinMax'),
    ...require('./uploadMasterItem'),
    ...require('./uploadStock'),
    ...require('./uploadWithdraw'),
    ...require('./uploadTemplate'),
    ...require('./uploadGourmet'),
    ...require('./uploadSKU'),
    ...require('./uploadBill'),
    ...require('./uploadSI'),
    ...require('./clearStock'),
    ...require('./clearSku'),
    ...require('./clearTemplate'),
    ...require('./clearMinMax'),
};
